version: "3.9"
services:

  nginx:
    container_name: nginx_payment_container
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8082:83"
    depends_on:
      - payment_app
    networks:
      - payment_app_network

  payment_app:
    container_name: payment_app
    build: .
    command: uvicorn API.settings:application --host 0.0.0.0 --port 85
    env_file:
      - ./project/payment_application.env
    ports:
      - "8081:8081"
    networks:
      - payment_app_network

  mongo_payment_database:
    container_name: mongo_payment_database
    networks:
      - payment_app_network

networks:
  payment_app_network:
    external: true
    name: global_project_network