version: "3.9"
services:

  nginx:

    container_name: nginx_payment_container
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8082:85"
    depends_on:
      - payment_app
    networks:
      - payment_app_network

  payment_app:

    container_name: payment_app
    build: .
    env_file:
      - ./project/payment_application.env
    environment:
      - DATABASE_URL=psql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8081/healthcheck/"]
      retries: 5
      interval: 10s
      timeout: 5s
    depends_on:
      - payment_postgresql_database
    networks:
      - payment_app_network

  payment_postgresql_database:

    container_name: postgresql_payment_database
    image: postgres:latest
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kirill
    ports:
      - "5438:5438"
    command:
      - -p 5438
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "payment_db"]
      retries: 5
      timeout: 10s
      interval: 15s
    networks:
      - payment_app_network

networks:
  payment_app_network:
    external: true
    name: global_project_network


