# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x08payments\"^\n\x13PaymentIntentParams\x12\x11\n\tproductId\x18\x01 \x01(\t\x12\x13\n\x0bpurchaserId\x18\x02 \x01(\t\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\t\">\n\x14PaymentSessionParams\x12\x11\n\tproductId\x18\x01 \x01(\t\x12\x13\n\x0bpurchaserId\x18\x02 \x01(\t\"6\n\x0cRefundParams\x12\x11\n\tpaymentId\x18\x01 \x01(\t\x12\x13\n\x0bpurchaserId\x18\x02 \x01(\t\"2\n\x16PaymentSessionResponse\x12\x18\n\x10PaymentSessionId\x18\x01 \x01(\t\"0\n\x15PaymentIntentResponse\x12\x17\n\x0fPaymentIntentId\x18\x01 \x01(\t\"\"\n\x0eRefundResponse\x12\x10\n\x08RefundId\x18\x01 \x01(\t2f\n\rPaymentIntent\x12U\n\x13\x43reatePaymentIntent\x12\x1d.payments.PaymentIntentParams\x1a\x1f.payments.PaymentIntentResponse2j\n\x0ePaymentSession\x12X\n\x14\x43reatePaymentSession\x12\x1e.payments.PaymentSessionParams\x1a .payments.PaymentSessionResponse2J\n\x06Refund\x12@\n\x0c\x43reateRefund\x12\x16.payments.RefundParams\x1a\x18.payments.RefundResponseb\x06proto3')



_PAYMENTINTENTPARAMS = DESCRIPTOR.message_types_by_name['PaymentIntentParams']
_PAYMENTSESSIONPARAMS = DESCRIPTOR.message_types_by_name['PaymentSessionParams']
_REFUNDPARAMS = DESCRIPTOR.message_types_by_name['RefundParams']
_PAYMENTSESSIONRESPONSE = DESCRIPTOR.message_types_by_name['PaymentSessionResponse']
_PAYMENTINTENTRESPONSE = DESCRIPTOR.message_types_by_name['PaymentIntentResponse']
_REFUNDRESPONSE = DESCRIPTOR.message_types_by_name['RefundResponse']
PaymentIntentParams = _reflection.GeneratedProtocolMessageType('PaymentIntentParams', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTINTENTPARAMS,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:payments.PaymentIntentParams)
  })
_sym_db.RegisterMessage(PaymentIntentParams)

PaymentSessionParams = _reflection.GeneratedProtocolMessageType('PaymentSessionParams', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTSESSIONPARAMS,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:payments.PaymentSessionParams)
  })
_sym_db.RegisterMessage(PaymentSessionParams)

RefundParams = _reflection.GeneratedProtocolMessageType('RefundParams', (_message.Message,), {
  'DESCRIPTOR' : _REFUNDPARAMS,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:payments.RefundParams)
  })
_sym_db.RegisterMessage(RefundParams)

PaymentSessionResponse = _reflection.GeneratedProtocolMessageType('PaymentSessionResponse', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTSESSIONRESPONSE,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:payments.PaymentSessionResponse)
  })
_sym_db.RegisterMessage(PaymentSessionResponse)

PaymentIntentResponse = _reflection.GeneratedProtocolMessageType('PaymentIntentResponse', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTINTENTRESPONSE,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:payments.PaymentIntentResponse)
  })
_sym_db.RegisterMessage(PaymentIntentResponse)

RefundResponse = _reflection.GeneratedProtocolMessageType('RefundResponse', (_message.Message,), {
  'DESCRIPTOR' : _REFUNDRESPONSE,
  '__module__' : 'payment_pb2'
  # @@protoc_insertion_point(class_scope:payments.RefundResponse)
  })
_sym_db.RegisterMessage(RefundResponse)

_PAYMENTINTENT = DESCRIPTOR.services_by_name['PaymentIntent']
_PAYMENTSESSION = DESCRIPTOR.services_by_name['PaymentSession']
_REFUND = DESCRIPTOR.services_by_name['Refund']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PAYMENTINTENTPARAMS._serialized_start=27
  _PAYMENTINTENTPARAMS._serialized_end=121
  _PAYMENTSESSIONPARAMS._serialized_start=123
  _PAYMENTSESSIONPARAMS._serialized_end=185
  _REFUNDPARAMS._serialized_start=187
  _REFUNDPARAMS._serialized_end=241
  _PAYMENTSESSIONRESPONSE._serialized_start=243
  _PAYMENTSESSIONRESPONSE._serialized_end=293
  _PAYMENTINTENTRESPONSE._serialized_start=295
  _PAYMENTINTENTRESPONSE._serialized_end=343
  _REFUNDRESPONSE._serialized_start=345
  _REFUNDRESPONSE._serialized_end=379
  _PAYMENTINTENT._serialized_start=381
  _PAYMENTINTENT._serialized_end=483
  _PAYMENTSESSION._serialized_start=485
  _PAYMENTSESSION._serialized_end=591
  _REFUND._serialized_start=593
  _REFUND._serialized_end=667
# @@protoc_insertion_point(module_scope)
