apiVersion: v1
kind: Secret
metadata:
  name: PaymentSecret

type: Opaque
stringData:
  POSTGRES_DB: payment_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Kirill
  POSTGRES_HOST: payment_postgresql_database
  POSTGRES_PORT: 5438

  DATABASE_URL: postgresql://postgres:Kirill@payment_postgresql_database:5438/payment_db
  DATABASE_HOST: payment_postgresql_database
  DATABASE_PORT: 5438

  TEST_DATABASE_HOST:  test_payment_database
  TEST_DATABASE_USER :  postgres
  TEST_DATABASE_PASSWORD :  Kirill
  TEST_DATABASE_PORT :  5437

  PAYMENT_APP_HOST: payment_app
  SONG_APPLICATION_SERVICE_HOST: song_app
  SUBSCRIPTION_APPLICATION_SERVICE_HOST: sub_app
  FRONTEND_APPLICATION_SERVICE_HOST: ''

  HTCI_API_KEY: 31d6ef4e-85ca-4370-b60b-6941a0f523ad
  HTCI_API_USER_ID: 6f88ade3-4ec0-46d0-bd96-bcddbe1b1cd8
