apiVersion: v1
kind: Deployment
metadata:
  name: payment-application-service
  namespace: payment_namespace
spec:
    template:
      name: payment-application-service
    selector:
      matchLabels:
        app: payment-application-service
    spec:
        containers:
          - name: application_server
            image: crazycoderrr/payment_service
            envFrom:
              configMapKeyRef:
                - name: PaymentConfigMap
            env:
              - name: STRIPE_API_SECRET
                valueFrom:
                  secretKeyRef:
                    - name: project-stripe-secret
                      value: STRIPE_API_SECRET
              - name: STRIPE_API_KEY
                valueFrom:
                  secretKeyRef:
                    - name: project-stripe-secret
                      value: STRIPE_API_KEY
            resources:
              requests:
                  cpu: "0.5"
                  memory: "1Gi"
              limits:
                  cpu: "0.5"
                  memory: "2Gi"
              ports:
                - name: http
                  targetPort: 8000
                  port: 8010
                  protocol: TCP

                - name: https
                  targetPort: 8000
                  port: 8010

            livenessProbe:
              exec:
                command: curl -f http://localhost:8000



