apiVersion: v1
kind: Deployment
metadata:
  name: payment-nginx-server
  namespace: payment_namespace
spec:
  template:
      name: payment-nginx-server
  selector:
      matchLabels:
          app: payment-nginx-server
  spec:
    hostname: payment_nginx_server
    containers:
      - name: nginx-server
        image: nginx:latest
        VolumeMounts:
          - MountPath: API/nginx/nginx.conf
            name: PaymentNginxConfiguration
        ports:
          - targetPort: 80
            port: 8010
            protocol: TCP
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: "0.5"
            memory: "1Gi"
    Volumes:
      - name: PaymentNginxConfiguration
        value: /etc/nginx/nginx.conf


