apiVersion: v1
kind: PersistentVolume
metadata:
  name: payment-postgres-persistent-volume
  namespace: payment-namespace
spec:
  claimRef:
    name: payment-postgres-persistent-volume-claim
    namespace: payment-namespace
  StorageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "5Gi"
  hostPath:
    path: "mnt/payment/data/"

  persistentVolumeReclaimPolicy: Retain
#  gcePersistentDisk:
#    size: "10Gi"
#    pgType: ex4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-postgres-persistent-volume-claim
  namespace: payment-namespace
spec:
  StorageClassName: manual
  accessModes:
    - ReadWriteOnlyOnce
  resources:
    requests:
      storage: "3Gi"
---

apiVersion: v1
kind: Service
metadata:
  name: payment-internal-service
  namespace: payment-namespace
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP

---

apiVersion: v1
kind: StatefulSet
metadata:
  name: payment-postgres-database
  namespace: payment-namespace
spec:
  template:
    spec:
      containers:
        - name: postgres_database
          image: postgres:latest
          envFrom:
            secretKeyRef:
              - name: postgres-secrets
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: PostgresDataVolume

          imagePullPolicy: IfNotPresent
      volumes:
        - name: PostgresDataVolume
          persistentClaim:
            claimName: payment-postgres-persistent-volume-claim

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: payment-namespace
stringData:
    POSTGRES_DB: payment_db
    POSTGRES_USER: postgres_user
    POSTGRES_PASSWORD: postgres_password

---